### ISSUE TITLE
Poor Alignment

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#189]
"Some of you sequences generated alignments that eliminated too many bases, a list is provided in ..."

Response:

The warning message you are getting indicates that some of your sequences have a poor alignment.  This can be caused by your sequences being flipped.  If you set flip=t, the align.seqs command will align your sequences and the reverse compliment of your sequences and choose the better alignment for you automatically.  

12.24.15

**Comment by FomenkyBridget** [comment]
Please could someone tell me how to set the flip=t

**Comment by mothur-westcott** [comment]
mothur > align.seqs(fasta=yourFastaFile, reference=yourReferenceFile, flip=t)

You may still get the warning, but those poorly aligned sequences will be removed in the screen.seqs command.

**Comment by FomenkyBridget** [comment]
thanks

-----Original Message-----

**Comment by FomenkyBridget** [comment]
Hi Sarah ,

The alignment step took longer as you mentioned and had the same warning but I ignored this time .
However I got to the filtering step;   filter.seqs(fasta=calves.trim.contigs.good.unique.good.align, vertical=T, trump=.)and the mothur interface was telling me close the program which I did but there was a message; your sequences are not the same
Do you think it should be because I did not set the start and end  on the screen step as below
screen.seqs(fasta=calves.trim.contigs.good.unique.align, count=calves.trim.contigs.good.count_table, summary=calves.trim.contigs.good.unique.summary,  maxhomop=8) instead of screen.seqs(fasta=calves.trim.contigs.good.unique.align, count=calves.trim.contigs.good.count_table, summary=calves.trim.contigs.good.unique.summary, start=1968, end=11550, maxhomop=8)
 if so should I include the start and end from my summary table??
Sorry for bothering you too much

Bridget


-----Original Message-----

**Comment by mothur-westcott** [comment]
It's not a bother, I am happy to help.  Are you using version 1.39?

**Comment by FomenkyBridget** [comment]
Yes I am using version1.39

**Comment by mothur-westcott** [comment]
Could you try it without the summary file?  You can either set the optimize parameter for start and end or set the values yourself.  

screen.seqs(fasta=calves.trim.contigs.good.unique.align, count=calves.trim.contigs.good.count_table, maxhomop=8, optimize=start-end)

screen.seqs(fasta=calves.trim.contigs.good.unique.align, count=calves.trim.contigs.good.count_table, maxhomop=8, start=1968, end=11550)

**Comment by sekhwal** [comment]
Hi..while run align.seqs, Mothur showing WARNING "Some of your sequences generated alignments that eliminated too many bases". I am trying to align 18sRNA samples against SILVA.seed_v123 reference database. I am not sure my reference database selection is correct for 18s rRNA. Please let me know ...
