### ISSUE TITLE
chimera.uchime doesn't find files with hyphen in their names

### ISSUE THREAD

**Issue by fmichonneau** [mothur/mothur#327]
Contrary to other mothur commands I have run (remove.seqs, county.seqs, pre.cluster), it seems that chimera.uchime doesn't work if the files specified contain hyphens (-) in their names. For instance,

```
mothur >  chimera.uchime(fasta=BCS_003_combined.trim.unique.macse.precluster.fasta,count='BCS-003_combined.trim.unique.macse.precluster.│bined.trim.unique.macse.precluster.FMMC-192.map
count_table', processors=10)                                       
Unable to open BCS. Trying default /home/francois/bin/mothur/BCS    
Unable to open /home/francois/bin/mothur/BCS. It will be disregarded.                                                                   
Unable to open 003_combined.trim.unique.macse.precluster.count_table.
Trying default /home/francois/bin/mothur/003_combined.trim.unique.macse.precluster.count_table                                        
Unable to open /home/francois/bin/mothur/003_combined.trim.unique.macse.precluster.count_table. It will be disregarded.                
[ERROR]: The reference parameter is a required.                     
Using 10 processors.                                               
[ERROR]: did not complete chimera.uchime. 
```

in this case, renaming the files so they don't include hyphens worked.

This is with mothur 1.39.5

**Comment by mothur-westcott** [comment]
Some of mothur's commands are designed to allow you to process multiple files sets at once.  The chimera.uchime command is one of those.  This means you could run a command like:

mothur > chimera.uchime(fasta=myfasta1.fasta-myfasta2.fasta, count=mycount1.count_table-mycount2.count_table, ...)

The above command will process both sets of files.  This is not a feature that is often used.  Although we recommend avoiding the '-' character, since it's a special character in mothur, you can escape it.  Here's how:

mothur > chimera.uchime(fasta=BCS_003_combined.trim.unique.macse.precluster.fasta,count=BCS\-003_combined.trim.unique.macse.precluster.│bined.trim.unique.macse.precluster.FMMC-192.map
count_table, processors=10)

I suspect the '|' character could give you issues as well, since it's a special character for the OS.  The name of your count file seems strange.  Did you create this file or did mothur?  Here's what the count file is supposed to look like, https://www.mothur.org/wiki/Count_File.

**Comment by fmichonneau** [comment]
Thanks for the feedback! Yes sorry the | is coming from a bad copy and paste from my terminal and is not part of the file name.
