### ISSUE TITLE
Options to run fungi dataset into Mothur

### ISSUE THREAD

**Issue by Vieira34** [mothur/mothur#334]
Hi Sarah,

Maybe is not the right place to make this question but... I'm working with a Fungi dataset (short reads ~250bp ITS2) and I'm using the MiSeq SOP to major steps. Have two basic question and maybe the answer is out there but I didn't find. 

1) So, for fungi, I should run the align command without specifying the region (I'm using the UNITE formatted database), I mean, like we do for Bacteria using V4 region, for example.

2) Have some way to run clulster.split command with different fragment size (between 240 -260bp)? I would like to generate the OTU table for this dataset. 

Thank for your attention and support!
Best,
Fabricio

**Comment by mothur-westcott** [comment]
https://w.mothur.org/forum/viewtopic.php?f=3&t=3949&p=19354&sid=7a4e8575bb58148f271eba6711475b1b

Pat comments, "if you're using ITS then you really can't do alignment because there isn't positional homology. I'd suggest using pairwise.seqs or pre.cluster. The next release of mothur will incorporate VSEARCH which will likely be a great help for people doing ITS. The caveat is that the OTU assignment may not be as good as what you'd get with pairwise.seqs/cluster"

The VSEARCH option is now part of mothur.  You can download our latest version here, https://github.com/mothur/mothur/releases.  Version 1.39 also includes our new clustering method which creates better quality OTUs while using less time and memory.  You can read about it in our paper, http://msphere.asm.org/content/2/2/e00073-17.

**Comment by brittonstrickland** [comment]
@Vieira34, did you have any luck successfully processing ITS data with mothur? I've been searching out some options, and would love to get mothur to work.
