### ISSUE TITLE
accept interleaved fastq file format

### ISSUE THREAD

**Issue by rrohwer** [mothur/mothur#362]
Hi, since some sequencing centers provide paired-end fastq files in the interleaved, 8-line format instead of as separate forward and reverse files, it would be great if mothur could accept this format in `make.contigs` or perhaps convert to the paired files format in `fastq.info`.

Thanks!

Robin

interleaved format meaning eg:
```
@read1forward
ATGCATCG
+
qualityscores
@read1reverse
ATGCATCG
+
qualityscores
@read2forward
ATGCGCGA
+
@read2reverse
ATGCGCAG
+
qualityscores
```

**Comment by mothur-westcott** [comment]
@pschloss, what do you think?

**Comment by pschloss** [comment]
This is the first I've heard of this as a format generated from a sequencing center. I think the separate fastq files would be preferred - it would be better and safer for the sequencing provider to do it than us since separate is the MiSeq's default. I'd put this on the back burner unless we see more requests for the feature.
