### ISSUE TITLE
sub.sample segmentation fault (core dumped)

### ISSUE THREAD

**Issue by xvazquezc** [mothur/mothur#417]
Hi,
I was running mothur (1.39.5) in our cluster following the MiSeq SOP, when I run into a `Segmentation fault (core dumped)` error similar to what is shown in #316 when executing `sub.sample()` using a shared file as input.
I followed some of the suggestions in #316, without any luck...
However I could get over it by just providing the list and count files used originally to produce the shared file instead.
I thought it could be good to keep the problem and solution recorded just in case somebody else runs into the same problem.
Cheers,
Xabi

**Comment by mothur-westcott** [comment]
Thanks for reporting this.  The issue is caused by our change to c++11.  We are working our way through mothur's source to update all threaded code which will resolve this issue.  The sub.sample command has already been modified. If you would like to use the fix, you can download the Thread_373 branch, https://github.com/mothur/mothur/tree/Threads_373.
