### ISSUE TITLE
[ERROR]: name mismatch in pcr.seqs.

### ISSUE THREAD

**Issue by cmkeg** [mothur/mothur#418]
Getting error with the command
pcr.seqs(fasta=silva.nr_v132.align, oligos=v4oligos.txt, keepdots=F, processors=4)
using oligo file that has worked in previous versions of mothur

**Comment by mothur-westcott** [comment]
Could you post the logfile and oligos file so I can take a closer look?

**Comment by fluidruid** [comment]
I was also getting an error message for pcr.seqs, but unsure if it's the same error message as cmkeg posted. Mine said:

[ERROR]: seqs are not aligned. When using start and end your sequences must be aligned.

Here is how I ran the command (silva version 132, mothur version 1.39.5) for V4 region:

pcr.seqs(fasta=silva.nr_v132.align, start=11894, end=25319, keepdots=F)

Is this fixed with mothur version 1.40.1? Or do I need to adjust the start/end coordinates for V4 region? Thanks!

**Comment by mothur-westcott** [comment]
I am able to run pcr.seqs(fasta=silva.nr_v132.align, start=11894, end=25319, keepdots=F) with no issues in version 1.40.1. Can you try upgrading?

**Comment by fluidruid** [comment]
Awesome, I will definitely upgrade. Thanks for getting back so quickly!

**Comment by mothur-westcott** [comment]
Can you try to run filter.seqs? The filter.seqs command requires aligned sequences as well and I'd like to see if you hit the same error.

mothur > filter.seqs(fasta=silva.nr_v132.align, vertical=t)

**Comment by fluidruid** [comment]
@mothur-westcott I did get the same error when I ran filter.seqs. Is there something wrong with my silva file? I downloaded it straight from the mothur wiki page and didn't do anything to the fasta file other than run it through the commands. Thanks

**Comment by mothur-westcott** [comment]
It sounds like it.  Could you try redownloading the file?

**Comment by fluidruid** [comment]
Ok redownloading the file seemed to fix the issue. Thanks!
