### ISSUE TITLE
trim.seqs

### ISSUE THREAD

**Issue by nikunjx** [mothur/mothur#434]
Hi, 

I am trying to trim my fastq files and I am using the following the command. 
fastq.info(fastq=1.fastq)
summary.seqs(fasta=1.fasta)
trim.seqs(fasta=1.fasta, qfile=1.qual, qwindowaverage=23, qwindowsize=25, minlength=280, processors=1, maxambig=0, maxhomop=8, keepforward=t, oligos=oligos.fasta, pdiffs=1)
I have included all the files containing the information of forward primer, reverse primer and barcode like this : 

primer	AGGTGAAGTAAAAGGTTCWTACTTAAA	CCTTCTAATTTACCWACWACTG	
primer	AGGTGAAGTAAAAGGTTCWTACTTAAA	CCTTCTAATTTACCWACAACAG	
primer	AGGTGAAGTTAAAGGTTCWTAYTTAAA	CCTTCTAATTTACCWACWACTG	
primer	AGGTGAAGTTAAAGGTTCWTAYTTAAA	CCTTCTAATTTACCWACAACAG
primer	AGGTGAAACTAAAGGTTCWTACTTAAA	CCTTCTAATTTACCWACWACTG	
primer	AGGTGAAACTAAAGGTTCWTACTTAAA	CCTTCTAATTTACCWACAACAG	
barcode	NNNNCGTACAGC	NNNNACACACAC	3_1
barcode	NNNNCTGGTGAT	NNNNAGTGCTAC	4_9
barcode	NNNNCTGGTGAT	NNNNACAGCACA	4_2
barcode	NNNNGTTGACCA	NNNNTACTATAC	5_3
barcode	NNNNGTTGACCA	NNNNGTCGTAGA	5_17
barcode	NNNNTGTGCGAT	NNNNGTTCGACT	6_14
barcode	NNNNGTACGACT	NNNNCGCTCTCG	7_5
barcode	NNNNATACCGGT	NNNNAGACTATG	9_7
barcode	NNNNACGACGAG	NNNNTACTATAC	10_3
barcode	NNNNATACCGGT	NNNNGTCGTAGA	9_17
But I am receiving am empty trim.fasta file.

Thanks
Nikunj

**Comment by mothur-westcott** [comment]
Could you upload your logfile and a subsample of your inputs so I can take a closer look?

mothur > sub.sample(fasta=1.fasta, size=500)
mothur > list.seqs(fasta=current)
mothur > get.seqs(qfile=1.qual)

**Comment by nikunjx** [comment]
It is a forward read fastq file. 
I did not include any barcodes file.

**Comment by mothur-westcott** [comment]
Okay, since it's not a paired read file you want a different format for you oligos file, https://mothur.org/wiki/Oligos_File.

forward	AGGTGAAGTAAAAGGTTCWTACTTAAA
forward	AGGTGAAGTTAAAGGTTCWTAYTTAAA
forward	AGGTGAAACTAAAGGTTCWTACTTAAA
barcode	NNNNCGTACAGC 	3_1
barcode	NNNNCTGGTGAT 	4_9
#barcode	NNNNCTGGTGAT 	4_2
barcode	NNNNGTTGACCA 	5_3
#barcode	NNNNGTTGACCA 	5_17
barcode	NNNNTGTGCGAT 	6_14
barcode	NNNNGTACGACT 	7_5
barcode	NNNNATACCGGT 	9_7
barcode	NNNNACGACGAG       10_3
#barcode	NNNNATACCGGT 	9_17

trim.seqs(fasta=1.fasta, qfile=1.qual, qwindowaverage=23, qwindowsize=25, minlength=280, processors=1, maxambig=0, maxhomop=8, keepforward=t, oligos=oligos.fasta, pdiffs=2, bdiffs=1)

You have duplicate forward primers and forward barcodes.  Does this file have a reverse fastq file associated with it? If so, I would recommend using the make.contigs command to trim the primers and barcodes and assemble the reads.

**Comment by nikunjx** [comment]
thank you . Now its working
