### ISSUE TITLE
Make a shared file from list and count constructs error

### ISSUE THREAD

**Issue by cons0063** [mothur/mothur#441]
Hi,

I am trying to make a shared file after running #classify.otu using .list, .count, .taxonomy, label=0.03
It doesn't load at all and just makes mothur freeze.
Is this happening to others? I can attach my files if that helps, I don't have the log files unfortunately (because it freezes and doesn't complete the command)!

Thanks.

**Comment by cynwydb** [comment]
Hi, I am having the same issue, just stalls, no error message. I was running the newest release on a PC.

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue. The issue is caused by a small bug in mothur's smart distancing code.  The smart distancing code allows mothur to find the next smallest distance when a label is asked for but not available in the file. I have fixed the issue and will release a version 1.40.1 shortly. As a workaround you can eliminate the label parameter and mothur will run for all the distances in your list file.

**Comment by mothur-westcott** [comment]
Could you try this version, https://github.com/mothur/mothur/releases/tag/v1.40.1?
