### ISSUE TITLE
Disk storage problems

### ISSUE THREAD

**Issue by juanjuanignacio** [mothur/mothur#446]
Hi again, I have another small problem.

At the time of doing the taxonomical assignment to get the .list file, I'm doing cluster.split, giving the fasta and the taxonomy file, everything is fine, it works fine, but there is a problem that I would like to solve: with 3 samples to see that my flow worked there was no problem, but when I wanted to run with the 21 samples cluster.split () creates over 200 .dist and many temporary files that exceed 1.5TB of storage. In my work we have bigmemory computers that have 2TB of RAM. Is there any way to evade this peak of temporary files? Using it or using only 64Gb RAM?

I've thought about using cluster () but it does not have a parameter for the taxonomy and I do not know if it creates a .list. Any way that cluster.split () does not split or split = False? Need some help. Thanks

I paste here a piece of the flow in case it helps:

time mothur "#unique.seqs(fasta=${output}/joined_fasta.fasta)" 
time mothur "#count.seqs(name=${output}/joined_fasta.names, group=${output}/mergegroups)" 
time mothur "#pre.cluster(fasta=${output}/joined_fasta.unique.fasta, count=${output}/joined_fasta.count_table, processors=16)"

export precluster_fasta=${output}/joined_fasta.unique.precluster.fasta
export precluster_count=${output}/joined_fasta.unique.precluster.count_table

time mothur "#classify.seqs(fasta=$precluster_fasta, count=$precluster_count, reference=$SILVA_ALIGN, taxonomy=$SILVA_TAX cutoff=80, processors=16)"

mv ${output}/joined_fasta.unique.precluster.*.wang.taxonomy ${output}/joined.taxonomy
export taxonomy=${output}/joined.taxonomy

time mothur "#cluster.split(fasta=$precluster_fasta, count=$precluster_count, taxonomy=$taxonomy, splitmethod=classify, taxlevel=4, cutoff=0.15, processors=16)"

export list1=${output}/joined_fasta.unique.precluster.opti_mcc.unique_list.list
mv $precluster_fasta ${output}/fasta.fasta
mv $precluster_count ${output}/count.count_table
mv $list1 ${output}/list.list

time mothur "#make.shared(list=$list1, count=$precluster_count, label=0.03)" 
time mothur "#classify.otu(list=$list1, count=$precluster_count, taxonomy=$taxonomy, label=0.03)"
 
export shared=${output}/joined_fasta.unique.precluster.opti_mcc.unique_list.shared
export constaxonomy=${output}/joined_fasta.unique.precluster.opti_mcc.unique_list.0.16.cons.taxonomy

time mothur "#make.biom(shared=$shared, constaxonomy=$constaxonomy, metadata=${METADATA})"

**Comment by mothur-westcott** [comment]
A few things:  

1. Try reducing the cutoff.  When using the opti method, you want to set the cutoff to the desired clustering distance.  The default we recommend is 0.03.

2. The cluster command creates a list file.  The cluster.split command is helpful with larger datasets because it clusters the sequences within their taxonomic classification and then combines the results.  This reduces the size of the distance matrices created because we don't calculate or store distances between taxonomies.

3. Are you following Pat's recommendations for processing the sequences before clustering. Removing chimeras, contaminants and combining redundant reads. Here's a link to Pat's example analysis, https://www.mothur.org/wiki/MiSeq_SOP.

4. You could almost change the taxlevel to reduce the size of the distance matrices created.
