### ISSUE TITLE
within sum-of-squares in mothur's amova is different from adonis

### ISSUE THREAD

**Issue by soonhwee** [mothur/mothur#473]
Hello, 

I noticed that the SSw output in amova from mothur is different from what I get in vegan-adonis. The total sum-of-squares are the same in both, though. I could not find the formula that is used to calculate SSw in adonis, but it can't be using a different SSw formula when its total sum-of-squares is the same as amova, can it?

By the way, I'm using mothur version 1.40.3. Thanks!

**Comment by metajinomics** [comment]
Hi soonhwee,

I think it is not a bug. It is because vegan-adonis use different method to calculate distance matrix. Vegan use “bray” for default. Mothur SOP use Yue & Clayton dissimilarity (Thetayc). When I tried to use same method of distance matrix, both Mothur and R(vegan) gives same result(Sums of square). Here is the example:

Frist, this is the output following Mothur SOP
mothur > amova(phylip=stability.opti_mcc.thetayc.0.03.lt.ave.dist, design=mouse.time.design)
Early-Late	Among	Within	Total
SS	0.629147	0.554503	1.18365
df	1	17	18
MS	0.629147	0.0326178
Fs:	19.2884
p-value: <0.001*


Second, now I use the same distance matrix in R(vegan)
This is the output of vegan(adonis)
> adonis(di ~ as.factor(si$time))

Call:
adonis(formula = di ~ as.factor(si$time)) 

Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

                   Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
as.factor(si$time)  1   0.62915 0.62915  19.288 0.53153  0.001 ***
Residuals          17   0.55450 0.03262         0.46847           
Total              18   1.18365                 1.00000           
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


I hope this answers your question.
