### ISSUE TITLE
how to use pcr.seqs 

### ISSUE THREAD

**Issue by zhangbw777** [mothur/mothur#481]
Hello
I am trying to use pcr.seqs command 
pcr.seqs(fasta=reference, )

to cut the reference for alignment.
The first question is if I want to use green gene as reference. Which reference should I use?
I downed the reference for alignment which gives me **gg_13_8_99.refalign** which is not a fasta file. should I use it as the reference or should I use the **gg_13_8_99.fasta** from the reference for taxonomy as the reference in this part?

another question is if I have the forward and reverse primers. How can I use them? The tutorial says I can used **pdiffs** and **rdiffs**, however, when I tried these commands below, none of them works

pcr.seqs(fasta=gg_13_8_99.refalign, pdiffs=CCTAYGGGRBGCASCAG, rdiffs=GGACTACNNGGGTATCTAAT)

pcr.seqs(fasta=gg_13_8_99.fasta, pdiffs=CCTAYGGGRBGCASCAG, rdiffs=GGACTACNNGGGTATCTAAT)

Could someone please show me how to use this command properly?

Thanks for your help
Bowen

**Comment by rtrpaine** [comment]
Hi Bowen,

I have pasted my command below. I'll preference this by saying pcr.seqs is the first command I used after make.contigs (v 1.39.5). I am analyzing 12S rRNA for fish metabarcoding. My fish community generally only has two or less differences in the forward primer, but you can experiment with changing the pdiffs and rdiffs values (e.g., pdiffs=2, rdiffs=2). Pdiffs/rdiffs allows pcr.seqs to match your primer from your oligo file to a given sequence as along as it only has 2 differences (references the example above). It will trim your sequences of the primers and anything outside of them. 

Make sure you have the fasta, group, and oligo file you need. 

I created my oligo file (.TXT) using Notepad++, but a .csv file could work too in Excel. If creating a .TXT file, it should look like this:

primer AGTGGATGTAGT CGATGCCGAGTCGTA,

where you type the work 'primer' followed by a space, then you type your forward primer sequence followed by a space, and finally the non-reverse compliment sequence of your reverse primer (this is where I had most of my issues)


Pcr.seqs(fasta=180628_DUCKtest_stability.trim.contigs.fasta, group=180628_DUCKtest_stability.contigs.groups, oligos=PCR_oligos.txt, pdiffs=3, rdiffs=3)

I hope this helps!

Cheers

**Comment by zhangbw777** [comment]
Hello

Thanks for your information.There is one part of the code I am still not
quite sure, in your code you used pdiff=3, rdiffs=3, where is this 3 come
from, what does it stand for?

Thanks for your help
Bowen



2018-06-30 23:34 GMT+10:00 rtrpaine <notifications@github.com>:

**Comment by rtrpaine** [comment]
Hi Bowen,

What pdiifs/rdiifs do are tells mothur to allow a certain amount of
differences between the forward (pdiffs) and reverse (rdiffs) primers and
the sequence she is matching them to.

In the example I gave you, 3 is an arbitrary number. I think for my project
I am probably going to use pdiffs/rdiffs=2. This is because I have aligned
2/3 of my fish community to my primers and I have seen that they differ by
2 basepairs at most. You might just have to experiment with this like I
did. I know that a lab at my school does a lot of MiSeq runs with 16S and
they use pdiffs/rdiffs=3. The lower this value the more strict you are
being, e.g. pdiffs/rdiffs=0 would mean your primers have to exactly match
to your sequences. They don't have to be the same either if that was clear,
e.g. pdiis=2 and rdiffs=1.

I hope this clarified some things. Please feel free to ask if you have more
questions.

Cheers,

Robert

**Comment by zhangbw777** [comment]
Hello I tried to create the oligos file using the way you mentioned, however, mothur doesn't like it. Is it because I am using the 1.36 version? I realize there is a 1.40.5 version, and I have downloaded it, but looks like my mothur is still 1.36, how am I able to ungrade my mothur?

thanks for your help

**Comment by mothur-westcott** [comment]
https://mothur.org/wiki/Frequently_asked_questions#I_installed_the_latest_version.2C_but_I_am_still_running_an_older_version
