### ISSUE TITLE
cluster.split error

### ISSUE THREAD

**Issue by Tegan2404** [mothur/mothur#542]
![1e36d995-5306-45da-804a-6e22889aba1a](https://user-images.githubusercontent.com/44367259/47293354-d2845780-d601-11e8-9f28-d70b7205b389.jpeg)
Hi,

I am new to mothur and am following the MiSeq SOP. 

dist.seqs has run fine, however when I come to do cluster it just fails and crashes. I have therefore tried to do cluster.split instead but it has thrown up these errors saying it cannot open the temp files. All of the correct files are in the C drive, please can someone help?

**Comment by mothur-westcott** [comment]
What version of mothur are you using? 

How many unique sequences do you have? I assume the cluster command failed because the distance matrix was too large. Have you read Pat's blog about this issue, http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/?

Is there enough disk space on the C drive for the files mothur will create when splitting?
