### ISSUE TITLE
rarefaction.single processors parameters remove

### ISSUE THREAD

**Issue by LuffyLuffy** [mothur/mothur#544]
Hi Schloss,

Thanks for your nice working of mothur.

It is said that the speed of rarefaction.single has been increased.

However, when I calculate the rarefaction of the diversity index, it seems slower with the removing of processors parameters.

rarefaction.single(shared=otus.shared,calc=sobs-chao-shannon,groupmode=f,freq=100,processors=5)

Do you suggest that we go back to the old version for quicker calculation?

**Comment by pschloss** [comment]
Thanks for your question - could you possibly post it at http://forum.mothur.org?

**Comment by mothur-westcott** [comment]
Removed parallelization in version 1.40, because current implementation was not thread safe. To reintroduce the processors option we will need to rework the division of work between the processors or rewrite the classes used by rarefaction.single to be thread safe, perhaps both.

Perhaps, division of work could be done by sample?? This would not add parallelization for use with list files, but would parallelize the command with shared files. Underlying classes may still need a rewrite.
