### ISSUE TITLE
Segmentation fault (pre.cluster)

### ISSUE THREAD

**Issue by stritttt** [mothur/mothur#611]
I am using mothur 1.42.1 version.  Everytime when i run pre.cluster command , i got an segmentation fault error message.
However, this does not seem to be a server memory or core issue.

And using version 1.39.5 did not cause any problems.
I don't know why this is happening.

**Comment by mothur-westcott** [comment]
Could you send your log file and input files to mothur.bugs@gmail.com?

**Comment by mothur-westcott** [comment]
The issue is caused by your group names. The "-" character is used within mothur to separate group names, labels, taxonomies, ect. Mothur is trying to split your samples into groups that don't exist.  For example:

"Running command: split.groups(groups=U10K-13-U10K-14, fasta=stability.trim.contigs.good.unique.good.filter.unique.fasta, count=stability.trim.contigs.good.unique.good.filter.count_table)"

The split.groups command is trying to find reads for U10K, 13, U10K and 14, but they don't exist. Changing the "-" character to "_" should resolve the issue.
