### ISSUE TITLE
How to generate precluster.names file in v1.42.0?

### ISSUE THREAD

**Issue by caroline-u** [mothur/mothur#616]
Hi,
I have another issue with the new version 1.42.0. When using the command
`pre.cluster(diffs=1, group=current, name=current)`

> Using Test.contigs.good.pick.good.abund.groups as input file for the group parameter. 
> Using Test.trim.contigs.good.unique.pick.good.filter.abund.names as input file for the name parameter.
> Using Test.trim.contigs.good.unique.pick.good.filter.unique.abund.fasta as input file for the fasta parameter.

I've received the following output files (v1.39.5):

> Test.trim.contigs.good.unique.pick.good.filter.unique.abund.precluster.names
> Test.trim.contigs.good.unique.pick.good.filter.unique.abund.precluster.fasta

By this I could run `count.seqs` afterwards to get a current .count_table (xxx.precluster.count_table). However, with v1.42.0 I only receive:

> Test.trim.contigs.good.unique.pick.good.filter.unique.abund.precluster.fasta
> Test.trim.contigs.good.unique.pick.good.filter.unique.abund.precluster.count_table

I also tried to change the `pre.cluster` command by using `count=current` instead or only the name file (`name=current`), both didn't produce any other output files than shown above. 

Any idea how I can produce an updated name file (xxx.precluster.names)? I need this file to continue the next steps with the correct number of sequences...

Thanks!
Caro

**Comment by mothur-westcott** [comment]
As the size of datasets grow, the names files become increasingly large and slow to process. We modified the pre.cluster command in version 1.42.0 to save memory and time. Part of the improvements were the phasing out of the name / group file for the pre.cluster command. Mothur converts the name and group files to create a sparse count table and uses this table for the pre.cluster command. The count table outputted by pre.cluster can be used by downstream commands in place of the names and groups file.

**Comment by caroline-u** [comment]
Ok, it would be great to get the option for outputting name files in future back again. 

Nevertheless, I've tried now the following workaround to get a name file. After `pre.cluster(diffs=1, group=current, name=current)` I've added the following to commands:

`list.seqs(count=test.precluster.count_table)` (which was the output from the `pre.cluster` command)
> Output File Names: 
> test.precluster.accnos

`get.seqs(accnos=test.precluster.accnos, name=previous.names)` (name file from a previous step, in my case `split.abund`)

By this I got the name file I needed.

**Comment by mothur-westcott** [comment]
That will not give you an accurate name file. Let's look at a small sample:

names file:
seq1 seq1,seq2,seq3,seq4
seq5 seq5,seq6
seq7 seq7,seq8,seq9
seq10 seq10

group file:
seq1  group1
seq2  group2
seq3  group1
seq4  group2
seq5  group1
seq6  group2
seq7  group1
seq8  group2
seq9  group1
seq10  group2

Count file:
Representative_seq   total   group1   group2
seq1    4    2   2
seq5    2    1    1
seq7    3    2    1
seq10  1    0    1


Clustered count file:
Representative_seq   total   group1   group2
seq1    7    4   3
seq5    3    1    2

Accnos file from list.seqs:
seq1
seq5

name file from get.seqs:
seq1 seq1,seq2,seq3,seq4
seq5 seq5,seq6

You can see this process removes reads rather than clustering them. Is there a reason you want the names file instead of the count file? https://www.mothur.org/wiki/Count_File If you want the names file format from a count file, you can convert it using the deunique.seqs and unique.seqs commands.

mothur > deunique.seqs(fasta=yourPreClusteredFastaFile, count=yourPreClusteredCountFile) - creates a fasta and group file with redundant names

mothur > unique.seqs(fasta=current) - create a unique fasta and names file

**Comment by caroline-u** [comment]
Ok, thanks for clarifying the functioning of `list.seqs` and `get.seqs`. I wanted to get the name file, because I used it for most of the subsequent processing steps (e.g. `classify.seqs`, `chimera.uchime`, ...). I changed now everything towards only using the count file and now everything works again :)

**Comment by costamc** [comment]
Maybe it would be a good idea to change that or at least add a note to the 454 SOP. Not that many are still using that, but it took me a while trying to find the problem before running into this post.

**Comment by mothur-westcott** [comment]
Thanks for the suggestion, I will update the 454_SOP page.
