### ISSUE TITLE
make.biom not working with subsampled shared file

### ISSUE THREAD

**Issue by koopkaup** [mothur/mothur#617]
I have smaller number of OTUs in my shared file than in the constaxonomy file and the make.biom wiki page says Mothur is smart enough to handle shared files that have been subsampled.
However, this will stop with an error message:
[ERROR]: Your constaxonomy file contains 265231 otus and your shared file contain 3405 otus, cannot continue.

Is it a bug or did I do something wrong?

**Comment by mothur-westcott** [comment]
We changed the command to force matching files because users were inadvertently using mismatched files, resulting in downstream errors. We added the list.otulabels, get.otus and remove.otus commands to allow you to select the otus from your constaxonomy file that are present in the shared file. Here's how:

mothur > list.otulabels(shared=yourSharedFile) - list names of OTUs present in shared file
mothur > get.otus(constaxonomy=yourConsTaxonomyFile, accnos=*.otulabels) - select otus from shared file also present in the constaxonomy file.

Sorry for the confusion, I will update the wiki.
