### ISSUE TITLE
Mothur MiSeq SOP ERROR  i get no data after screen.seqs

### ISSUE THREAD

**Issue by ivargasp** [mothur/mothur#618]
Hi, It´s my first time using this pipeline.  I´ve been trying to run this command: 

screen. seqs With the values:  start=10263, end=23444) 

summary.seqs 

 Start   End     NBases  Ambigs  Polymer NumSeqs
Minimum:        10263   22568   249     0       3       1
2.5%-tile:      13862   23444   252     0       3       9272
25%-tile:       13862   23444   253     0       4       92719
Median:         13862   23444   253     0       4       185437
75%-tile:       13862   23444   253     0       5       278155
97.5%-tile:     13862   23444   253     0       5       361601
Maximum:        13875   26162   299     0       8       370872
Mean:   13861.9 23444.2 252.852 0       4.10254
# of unique seqs:       57495
total # of seqs:        370872

But, it is removing all my samples "Removing group XXX because all sequences have been removed". Also, it says that my .trim.contigs.good.unique.good.align is blank. 
What am I doing wrong?

Please help.

**Comment by mothur-westcott** [comment]
https://www.mothur.org/wiki/Screen.seqs#start_.26_end  The issue is caused by the start parameter setting.

The start parameter removes all reads that start AFTER the location specified, so since your minimum read starts at 10263 all reads are removed.

The end parameter removes all reads that end BEFORE the location specified, which will remove some of your reads.

Try setting start=13862, end=23444

**Comment by ivargasp** [comment]
Thank you, It worked!!!
