### ISSUE TITLE
dist.seqs, disk storage, and beating a dead horse. 

### ISSUE THREAD

**Issue by hbussan** [mothur/mothur#630]
Hello,

I am another new mothur user trying to figure out dist.seqs and cluster.split. 
I am running ~98 samples using V4 primers on MiSeq. I have extracted unique sequences and removed chimeras and undesirables according to the MiSeq SOP. I am also familiar with the blog post by Dr. Schloss and this post(https://github.com/mothur/mothur/issues/423). I am trying to figure out ways to decrease my .dist file size (which has gotten to be about 1 TB). I have 260,000 unique sequences and just over 7,000,000 total sequences. 

I ran dist.seqs with a cutoff of .1 (otherwise the computer would crash) and my cluster.split of .03 (which has been running for a week now with one processor and is very far from finishing). 

I have attached my log file. I think I have done the suggestions by the site - is there anything else I can do at this point or is this a lost cause? What wet bench things can I do to prevent this in the future? The MiSeq reported good quality, density and low error rate. 

[mothur.1559249356_upload.logfile.txt](https://github.com/mothur/mothur/files/3277563/mothur.1559249356_upload.logfile.txt)

**Comment by mothur-westcott** [comment]
A few recommendations:

1. When using the opti method, set your cutoff equal to the distance you want OTUs created for. Distances above the cutoff are ignored. 

2. Reduce the number of processors. Each processor used will load a distance matrix into memory. The more processors the more memory used.

3. Run cluster.split with a taxonomy, fasta and count file rather than a distance matrix.  Calculating the smaller distance matrices for each taxonomic group uses less time and memory than running dist.seqs and cluster.split with a full distance matrix.

4. Run cluster.split with cluster=false, then run again using the file option to avoid recalculating the small distance files if a memory crash occurs. This allows you to use more processors in the distance calculations and less in the clustering phase.  https://mothur.org/wiki/Cluster.split#file
