### ISSUE TITLE
Segmentation fault with chimera.vsearch command 

### ISSUE THREAD

**Issue by koopkaup** [mothur/mothur#672]
Both mothur versions (1.42.3 and 1.43.0) and vsearch version 2.13.3 give segmentation fault in chimera.vsearch command. 
chimera.vsearch(fasta=NGS00229.assembled.trim.pick.unique.fasta, count=NGS00229.assembled.trim.pick.count_table, dereplicate=t, processors=20)

None of the samples are empty. And I only got this warning for every group name:
group NuB2-1 contains illegal characters in the name. Group names should not include :, -, or / characters.  The ':' character is a special character used in trees. Using ':' will result in your tree being unreadable by tree reading software.  The '-' character is a special character used by mothur to parse group names.  Using the '-' character will prevent you from selecting groups. The '/' character will created unreadable filenames when mothur includes the group in an output filename.

Is this the reason?

**Comment by mothur-westcott** [comment]
Yes, the '-' character is likely the problem. The first thing the chimera.vsearch command does is divide the dataset by sample. The split.groups command is used to do this and would look something like:

mothur > split.groups(fasta=yourFastaFile, count=yourCountFile, groups=group1-group2...groupN)

If your group names contain '-' characters then the group names would not be found. Consider this:

groups=NuB2-1-NuB2-2

Mothur will look for groups NuB2, 1 and 2. Since those groups are not present the per sample files would not be created and the command would fail. Can you replace the '-' characters with '_' characters in the count file?

**Comment by koopkaup** [comment]
Yes, this was the case. Now it works.
