### ISSUE TITLE
Chimera searching very slow

### ISSUE THREAD

**Issue by ajwnewkirk** [mothur/mothur#687]
Let me know if this is a question better asked in another forum. I'm using mothur to do some QC on data from a highly multiplexed amplicon sequencing panel (~135 primer pairs x 48 samples). I'm having problems with chimera.vsearch running for too many (4+ days currently and <30% finished). From looking at the log files, it appears that the checking of each combination of sample x primer pair is being run sequentially rather than any parallelization happening. I thought I recalled reading in mothur docs somewhere that vsearch did not parallelize, but that is not what I understood from reading the vsearch github description. My mothur script is short and pasted below, so please let me know if there's something I've done in the workflow that's creating a problem. Thank you so much for your help.

set.dir(input=raw_seqs, output=/scratch/mothur, tempdefault=/scratch/mothur)
make.contigs(ffastq=Undetermined_S0_L001_R1_001.fastq, rfastq=Undetermined_S0_L001_R2_001.fastq, findex=Undetermined_S0_L001_I1_001.fastq, rindex=Undetermined_S0_L001_I2_001.fastq, processors=40, format=illumina1.8+, oligos=191018.oligos, bdiffs=0, pdiffs=0, checkorient=t, insert=25, trimoverlap=f)
rename.file(fasta=current, group=current, prefix=sal)
summary.seqs()
screen.seqs(fasta=current, group=current, maxambig=0, maxlength=325)
summary.seqs()
unique.seqs(fasta=current)
summary.seqs()
chimera.vsearch(fasta=current, name=current, group=current, dereplicate=t, processors=40)
remove.seqs(fasta=current, accnos=current, name=current, group=current, dups=t)
summary.seqs()
split.groups(fasta=current, group=current)
quit()

**Comment by mothur-westcott** [comment]
I recommend using a count file rather than the name/group combination. It is much faster. Also, this combination of commands may not be doing what you think. Let me explain.

chimera.vsearch(fasta=current, name=current, group=current, dereplicate=t, processors=40) - when dereplicate=t, if a sequence is found to be chimeric in a sample it is removed from that sample and not all samples
remove.seqs(fasta=current, accnos=current, name=current, group=current, dups=t) - dups=t, means remove read from all samples. This contradicts what the dereplicate=t is doing.

**Comment by ajwnewkirk** [comment]
Hi Sarah - thanks for the quick response! I was wondering if the different file formats make a difference, so I will try that. The explanation for the vsearch/remove options was also the clearest I've yet found. I appreciate the examples on the vsearch man page, but it obviously didn't help me get a total understanding of the interactions. You might also check the MiSeq SOP page - I follow it pretty closely for most of my scripts if I have any questions about which options to choose, and this setup is what I understood was what you use routinely for these commands. I will report back and see if this makes a difference.

**Comment by ajwnewkirk** [comment]
An update - I was checking on the progress of the original and updated scripts. Both are still running, but it does not look like using the count table and fixing the conflicting duplicates commands are improving speed much. I checked the logs and noticed that both are still at the stage where they are running split.seqs as a part of the vsearch command. Which suggests to me that the greatly increased file IO from having nearly 10k sample x primer pair combinations is the real problem for my (unusual) use case since this command appears to be sequentially writing out temporary files for each combo.

Questions:
1. Do you agree that the creation of the temp files is probably the issue? I'm already using the fastest storage we have for my output location, so I can't do anything else on my end to speed up the file IO.
2. Is there anything else I can try to speed this up? I've been struggling with this data set for about a month now and can't make any progress. I'm open to the most temporary and hacky of suggestions if it gets me moving and I can evaluate the quality of this data set.
3. I realize this use case isn't your core target. If you agree that something like parallelizing split.seqs would make a difference, how likely are you to implement that change in the near-term?

Thank you again!

**Comment by mothur-westcott** [comment]
The chimera.vsearch command is parallelized and divides the work by assigning each processor a set of the samples to process. Each process then calls the split.groups / get.seqs commands which find the names of the sequences present in each sample and selects the reads from the fasta file. This step requires reading the fasta input file. These new parsed files are sent to the vsearch program for analysis. The chimera.vsearch command then assembles the vsearch program results for you. This assembly includes editing the counts for the sequences in the count file to reflect which samples found which sequences to be chimeric.

1. The splitting of the dataset into individual samples is the source of the issue. With 10K samples mothur is reading the fasta file 10k times and writing 10K temp files for vsearch. This will use a lot of time and memory. 

2. You can run the chimera.vsearch command on the entire dataset without splitting by sample. We recommend the splitting by sample because its the more conservative approach. To run the command without parsing: 

NOTE: your count file cannot contain groups. You can remove the group columns manually or run the following to remove them:

mothur > deunique.seqs(fasta=yourFastaFile, count=yourCountFile) - create fasta file will all reads. This could be huge.
mothur > unique.seqs(format=count) - create count file without groups
mothur > chimera.vsearch(fasta=current, count=current, reference=self) - flag sequences chimeric in whole dataset
mothur > remove.seqs(fasta=current, count=yourCountFile) - remove chimeras from fasta and original count file that includes groups
 
3. Paralellizing split.groups would not improve the speed with the command.
