### ISSUE TITLE
How to select the "start" and "end" positions for screen.seqs

### ISSUE THREAD

**Issue by tkeertana** [mothur/mothur#689]
Hi everyone!
I came across the fact that my start and end positions are differing in the summary.seqs table which I will mention below. I want to know how one can select the correct start & end positions for our screen.seqs command in order to eliminate unwanted sequences. I have done V3-V4 sequencing of my sample with Illumina MiSeq. 
In fact, I experimented with trying two cases for the summary.seqs table below:

```
Start	End	NBases	Ambigs	Polymer	NumSeqs
Minimum:	1044	6098	17	0	3	1
2.5%-tile:	1044	13133	453	0	4	485
25%-tile:	1044	13871	499	0	5	4848
Median: 	1044	13871	514	0	5	9696
75%-tile:	1044	13871	516	0	5	14543
97.5%-tile:	1044	14286	529	0	7	18906
Maximum:	43053	43116	531	0	8	19390
Mean:	1046	13851	505	0	5
 of Seqs:	19390
```

1. start = 1044 and end = 13871, for which at the very end of the protocol, after the classify.otu command OTU count is 1063 OTUs
2. start = 1044 and end = 14286, for which at the very end of the protocol, after the classify.otu command OTU count is 218 OTUs

How should I go about to select these positions if I am getting such large differences in this sample?
Kindly help me as soon as possible.

Regards,
Keertana

**Comment by pschloss** [comment]
Hi,

The parameters you probably want are start=1044 and end=13871. This probably results in a loss of  2000 to 4000 sequences. If you use the second set of parameters you list, you'll likely be losing about 17000 sequences since not many of the sequences end at or after 14286. Because of the large reduction in the number of sequences, the number of OTUs would also be far fewer than what you have with the first approach.

**Comment by tkeertana** [comment]
Dear Dr Schloss,
Thank you so much for the explanation. I figured as much but was waiting to
hear from the experts themselves. This will be very helpful for me.

Sincerely,
Keertana Tallapragada

MSc Molecular Microbiology
University of Hyderabad,
Hyderabad, India.
Email: *tkeertana@gmail.com <tkeertana@gmail.com>*
