### ISSUE TITLE
split.abund unexpected behaviour in 1.44.1

### ISSUE THREAD

**Issue by didillysquat** [mothur/mothur#715]
Hi there,

I think there is something going wrong with the split.abund command in 1.44.1. When I run it with a fasta and names option (as below). The .names file that I use gets overwritten with a blank file.

When I run exactly the same command in 1.43, with the same files, I get the expected behaviour. I.e. a work.abund.names and a work.rare.names.

Thanks,

Ben

P.s. I'm also a little confused about what these '.pick' files are that mothur is telling me are being output, but I'm not seeing them in my directory. Is this new behaviour for 1.44?

```
mothur > split.abund(fasta=work.fasta, name=work.names, cutoff=2)
/******************************************/
Running command: get.seqs(dups=t, accnos=work.rare.accnos, name=work.names, fasta=work.fasta)
Selected 8752 sequences from your name file.
Selected 8326 sequences from your fasta file.

Output File Names:
work.pick.names
work.pick.fasta

/******************************************/
Done.
/******************************************/
Running command: get.seqs(dups=t, accnos=work.abund.accnos, name=work.names, fasta=work.fasta)
Your file does not contain any sequence from the .accnos file.
Selected 0 sequences from your name file.
Selected 594 sequences from your fasta file.

Output File Names:
work.pick.names
work.pick.fasta

/******************************************/
Done.

Output File Names: 
work.rare.accnos
work.abund.accnos
work.names
work.rare.fasta
work.names
work.abund.fasta
```

**Comment by mothur-westcott** [comment]
Could you send your input files and logfile to mothur.bugs@gmail.com?

**Comment by mothur-westcott** [comment]
I was able to find the source of the issue which will be corrected in our next release. You are correct, mothur was accidentally overwriting the original names file before the get.seqs command was run. The bug only effects split.abund when run with a names file. As a workaround you can run the command with a count file.

mothur > summary.seqs(fasta=work.fasta, name=work.names)
mothur > count.seqs(name=current) - create a count file from your name file
mothur > split.abund(fasta=current, count=current, cutoff=2) - split by abundance using the count file instead of names file.
mothur > list.seqs(fasta=current) - list seqs in rare file
mothur > get.seqs(name=current, dups=t) - select rare names from original names file
mothur > rename.file(name=current, fasta=current, prefix=rare) - rename rare files
mothur > summary.seqs(fasta=rare.fasta, name=rare.names) - summarize rare files
mothur > list.seqs(fasta=work.abund.fasta) - list abundant sequences
mothur > get.seqs(name=work.names, dups=t) - select abundant names from original names file
mothur > rename.file(name=current, fasta=current, prefix=abund) - rename abundant files
mothur > summary.seqs(fasta=abund.fasta, name=abund.names) - summarize abundant files

**Comment by didillysquat** [comment]
Many thanks for your help!
