### ISSUE TITLE
[ERROR]  has occurred in the Utils class function mothurConvert-int

### ISSUE THREAD

**Issue by sfidemw** [mothur/mothur#722]
I received this error when doing my microbial analysis with the MiSeq SOP.

mothur > screen.seqs(fasta=16s.trim.contigs.good.unique.align, count=16s.trim.contigs.good.count_table, summary=16s.trim.contigs.good.unique.summary, start=11895, end=25318. maxhomop=8)

[ERROR]: 25318.RAM used: 3.66693Gigabytes . Total Ram: 62.8462Gigabytes.
has occurred in the Utils class function mothurConvert-int. 
Please contact Pat Schloss at mothur.bugs@gmail.com, 
and be sure to include the mothur.logFile with your inquiry

I attempted to email but it was returned. If someone could help me, I would appreciate it. I have attached my mothur log file as requested.
[mothur.1589935943.logfile.txt]
(https://github.com/mothur/mothur/files/4684333/mothur.1589935943.logfile.txt)

**Comment by mothur-westcott** [comment]
mothur > screen.seqs(fasta=16s.trim.contigs.good.unique.align, count=16s.trim.contigs.good.count_table, summary=16s.trim.contigs.good.unique.summary, start=11895, **end=25318.** maxhomop=8)

The issue is caused by the end parameter. You have a period instead of a comma separating the parameters. Try this instead:

mothur > screen.seqs(fasta=16s.trim.contigs.good.unique.align, count=16s.trim.contigs.good.count_table, summary=16s.trim.contigs.good.unique.summary, start=11895, **end=25318,** maxhomop=8)

**Comment by sfidemw** [comment]
You were correct! That was the issue. Thank you.
