### ISSUE TITLE
problems with get.oturep command

### ISSUE THREAD

**Issue by itiago** [mothur/mothur#738]
Hi
I've done a full analyses of a data set and at the end I wanted to retrieve results to be analysed in picrust.
First I did 

mothur > get.oturep(column=UCGeno.trim.contigs.good.unique.good.filter.unique.precluster.pick.dist, list=UCGeno.trim.contigs.good.unique.good.filter.unique.precluster.pick.opti_mcc.0.03.pick.list, count=UCGeno.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.pick.count_table, fasta=UCGeno.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta)

You did not provide a label, using 0.03.
AAError: Sequence 'M03882_73_000000000-D3HHJ_1_1101_25378_8342' was not found in the name or count file, please correct

so I tried to update the count file:

count.seqs(name=UCGeno.trim.contigs.good.names, count=UCGeno.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.pick.count_table)
Output File Names: 
UCGeno.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.pick.sparse.count_table

and then repeated the get.oturep command with the up-to-date file but the same error apeares.
What am I doing wrong?
Thanks for any help.
I'm sending in attach the log file

[mothur.1594305209.logfile.txt](https://github.com/mothur/mothur/files/5075090/mothur.1594305209.logfile.txt)

**Comment by mothur-westcott** [comment]
The files contain different numbers of sequences. Let me explain:

UCGeno.trim.contigs.good.unique.good.filter.unique.precluster.pick.dist was created from the fasta file before the rare OTUs were removed. It contains distances from sequences you removed with remove.rare.

UCGeno.trim.contigs.good.unique.good.filter.unique.precluster.pick.opti_mcc.0.03.pick.list does not contain any of the reads removed from OTUs with abundance < 10. This causes a mismatch with the distance file.

The fasta and count files match the list file, because you used the list.seqs and get.seqs commands to remove the sequences in the rare OTUs.

The bug occurs when mothur reads the distance file and tries to find the abundances for each read in the distance file. The abundances are stored in the count file and the count file does not include all the reads.

To remove the extra distances from your column file, try this:

mothur > list.seqs(list=UCGeno.trim.contigs.good.unique.good.filter.unique.precluster.pick.opti_mcc.0.03.pick.list)

mothur > get.dists(column=UCGeno.trim.contigs.good.unique.good.filter.unique.precluster.pick.dist, accnos=current)

mothur > get.oturep(column=current, list=current, count=UCGeno.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.pick.count_table, fasta=UCGeno.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta)

**Comment by itiago** [comment]
Thank you Sarah
That helped a lot!
I managed to get the OTU rep.
All best
Igor
