### ISSUE TITLE
Version 1.44.3 make.contigs command doesnt produce qfile (.qual).

### ISSUE THREAD

**Issue by stormsz** [mothur/mothur#745]
No matter what i try, the make.contigs command doesn't produce .qual files.
I was using an older version without problems so I'm guessing this is a bug, or I am doing something wrong.
I do realize the qfile option is False by default and I am using qfile=t.

`make.file(inputdir=.)`
`make.contigs(file=stability.files, oligos=fully_degenerated_rbcL_primers.oligos, pdiffs=1, qfile=t)`

log: https://pastebin.com/2vBjBNBk

I have also tested the exact same dna .fastq files on the older version (1.41.something) and the .qual is created with the make.contigs command.

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue. The make.contigs command was adding the path to your qfile option, so qfile=t became qfile=fullPath/t which is not equal to true. This bug will be fixed in our next release. 

One thing to note: The assembled quality scores outputted by mothur cannot be used for downstream quality screening. The score calculations are modeled after pandseq's method. Here's a link to the explanation from their documentation, https://github.com/neufeld/pandaseq#the-scores-of-the-output-bases-seem-really-low-whats-wrong.
