### ISSUE TITLE
remove.rare issue when using both list and shared options

### ISSUE THREAD

**Issue by Puumanamana** [mothur/mothur#775]
Hi,

I'm trying to remove any OTU in my dataset with a total abundance of 1. I have both a shared and a list file, and I would like to filter both files at the same time. Therefore I do:
`remove.rare(list=current, shared=current)`
```
For the listfile you must select one label, using first label in your listfile.
Your file contains only rare sequences.
0

Output File Names:
mothur_remove_lineage.100.0.pick.list
mothur_remove_lineage.100.0.pick.shared
```

The list file returned is empty, why the shared file is correctly filtered. Instead, I would have expected to have a list with the same OTUs in my shared file.
My guess is that the list file is being filtered for OTUs with a prevalence of 1 (instead of abundance), since my test data only contains OTUs that appear once in various samples. 

EDIT: I also have a similar issue with `sub.sample()`: when I use both shared and list files, the list file is not updated (while some OTUs are dropped). Neither problem occur when I use a count file.

**Comment by mothur-westcott** [comment]
Does the list file have a count file associated with it? If so, you will want to include it so mothur is aware of the redundant sequences and can calculate the correct OTU abundances in the list file. Try this:

mothur > remove.rare(list=current, count=current, shared=current) 

or alternatively

mothur > remove.rare(shared=current) - remove rare OTUs from shared file
mothur > list.otus(shared=current) - list OTUs in shared file
mothur > get.otus(list=current, accnos=current) - select OTUs present in shared file from the list file

**Comment by Puumanamana** [comment]
Thank you for your help.
I was thinking of dropping the count file at this point of the analysis and only focus on the OTU abundances. However, I'm encountering a few issues when using shared files (without counts). 
If I understood corectly, remove.rare() is removing whole OTUs (not individual low abundance contigs), so why are the individual counts necessary to compute the abundance? 
Also, the second approach you describe would work in my case, but I'm still confused why the one-line command would not be valid as well.

**Comment by mothur-westcott** [comment]
Let's look at a simple example:

list file

label numOTUs OTU1 OTU2 OTU3 
0.03   3    seq1,seq6  seq3  seq4

count file:

Representative_Sequence	total	group1   group2 
seq1   5   3  2
seq3  2   1  1
seq4  1  0 1
seq6  3  2  1

The abundance of an OTU is the sum of the abundances of the sequences it contains.

With a count file:

Abundance of OTU1 = (abundance of seq1) + (abundance of seq6)
Abundance of OTU1 = 5 + 3 = 8

Abundance of OTU2 = (abundance of seq3) 
Abundance of OTU2 = 2

Abundance of OTU3 = (abundance of seq4) 
Abundance of OTU3 = 1

Only OTU3 is considered rare.

Without a count file each OTUs abundance is the count of the seqs present in the OTU:

Abundance of OTU1 = (abundance of seq1) + (abundance of seq6)
Abundance of OTU1 = 1 + 1 = 2

Abundance of OTU2 = (abundance of seq3) 
Abundance of OTU2 = 1

Abundance of OTU3 = (abundance of seq4) 
Abundance of OTU3 = 1

OTU2 and OTU3 are both considered rare because mothur is unaware that seq3 represents 2 reads.

**Comment by Puumanamana** [comment]
I understand that without any count information, you can't remove rare OTUs. However, in my case, I have the shared file that contains OTU counts. So mothur should be able to remove them from both the shared and list file. 
In you example, the shared file would say directly (without seeing the individual counts of seq1...6):
Abundance of OTU1  = 8
Abundance of OTU2 = 2
Abundance of OTU3 = 1
That is what is probably what is happening when you do `remove.rare(shared=current)`. However, why not filter the list file at the same time when you add the list argument on top of the shared argument?

**Comment by mothur-westcott** [comment]
The command allows you to process the list and shared files separately by design. It does not rely on the OTUs that are found to be rare in one file to calculate the rare OTUs in the other.  Processing the shared file with remove.rare, and then selecting the OTUs from your list file may be a better approach for you to avoid downstream mismatches.

**Comment by Puumanamana** [comment]
I see, thank you for the explanations
