### ISSUE TITLE
neddleman-Wunsch for nanopore full length long reads 16S gene

### ISSUE THREAD

**Issue by jianshu93** [mothur/mothur#811]
Dear Mother team,

I am using the classify.seqs command  for classify long 16S gene sequenced by nanopore MinION, I am wondering what exactly Needleman-Wunsch was used for alignment, so called ends free (semi-global) or just global. This is important because there are several cases where the full length 16S is longer than database 16S, so if the extra part was penalized when aligning, it is possible that best identity matches will be missed. This is also for the MiSeq short reads, semi-global should be used. This will be worse for longer reads because it would be too long to be penalized if using normal global alignment.

Thanks,

Jianshu

**Comment by pschloss** [comment]
Do you mean `classify.seqs` or `align.seqs`. Needleman-Wunsch shouldn't be used for classification since the preferred method is a kmer-based approach. Regardless, if your sequences are longer than those in the database then you should probably trim your sequences to the same length as those in the database or get different database sequences. Sometimes this happens because people leave their primers on their sequences. It is generally considered a best practice to remove primer sequences.

For `align.seqs` we haven't seen a performance problem if you align a sequence longer than the reference. However, the bases that are longer than the database will get converted into `.` characters in the alignment.
