### ISSUE TITLE
system(cd) not moving me? 

### ISSUE THREAD

**Issue by krmaas** [mothur/mothur#833]
Hi Sarah

I'm trying to help someone set up mothur on their mac 11.6 and am having issues with (I assume) mac security. Have moved mothur exec into their data directory, launch it by double clicking because we can't see mothur when in terminal. This opens mothur but in their home dir, not the dir where the exec is? system(pwd) shows me where we are, but system(cd folder/I/want) doesn't move me?

help?
thanks
Kendra

**Comment by mothur-westcott** [comment]
Hi Kendra,
  Mothur now has built in keywords to store and remember paths for you. The set.dir command, https://mothur.org/wiki/set.dir/ <https://mothur.org/wiki/set.dir/>, mothurfiles parameter automatically stores mothur’s executable location and you can set other locations separated by ‘;'. I recommend using it rather than the system command to change directories. Here’s an example:

mothur > system(pwd)
/Users/swestcott


mothur > get.current()

Current RAM usage: 0.00552368 Gigabytes. Total Ram: 32 Gigabytes.

Current files saved by mothur:
processors=16

Current default directories saved by mothur:
	/Users/swestcott/Desktop/MothurStuff/1.48.0/


Current working directory: /Users/swestcott/

Output File Names: 
current_files.summary

mothur > set.dir(mothurfiles='/Users/swestcott/Desktop/MothurStuff/1.48.0/;/Users/swestcott/Desktop/MothurStuff/release/', inputdir=./desktop)
Setting input directories to: 
	/Users/swestcott/desktop/

Mothur's directories:
mothurfiles=
	/Users/swestcott/Desktop/MothurStuff/1.48.0/
	/Users/swestcott/Desktop/MothurStuff/release/

mothur > get.current()

Current RAM usage: 0.00582123 Gigabytes. Total Ram: 32 Gigabytes.

Current files saved by mothur:
processors=16

Current default directories saved by mothur:
	/Users/swestcott/Desktop/MothurStuff/1.48.0/
	/Users/swestcott/Desktop/MothurStuff/release/


Current working directory: /Users/swestcott/

Output File Names: 
current_files.summary

You can also use the mothurhome keyword, https://mothur.org/wiki/set.dir/#mothurhome <https://mothur.org/wiki/set.dir/#mothurhome>, as a shortcut in any filename. 

Kindly,
  Sarah
