### ISSUE TITLE
How does mothur "choose" to taxonomically classify a sequence, when multiple sequences in a database are the same?

### ISSUE THREAD

**Issue by rtrpaine** [mothur/mothur#844]
Hello,

I am using mothur for HTS of fish communities. I have curated my own database to which I can use classify.otus. I have a database that includes well over 200 species, represented by over 800 sequences. Some "species" have the exact same sequence, i.e., Species A and Species B are 100% match to each other. Given that my target sequence is ~170 bp, this is plausible and has been shown with the primers I am using. (Although individuals that reference sequences are generated from could have been misidentified too).

I conducted a preliminary run to see what would happen with the same sequence represented as two different species.  In the preliminary data, Mothur classified some sequences as Species A, and others as Species B. In case it matters, Mothur classified 326,005 sequences as Species A, and 26 sequences as Species B. I would think there might be a clear pattern of classification when two species share the same sequence, but it does not appear to be. If they have the same reference sequence, how can Mothur differentiate sequences as one species or the other? 

I am trying to determine if there is some robust mechanism taking place that Mothur's results are accurate, or if I need to remove one or both species from the database. The system I am working in is abundantly populated by a number of invasives, many from the aquarium trade. Therefore, we are not really sure what could be there; and we wanted to try and include as many species as possible.

Any advice or help would be greatly appreciated. 

Cheers,

**Comment by pschloss** [comment]
Hi there - I assume you're using `classify.seqs` with your own database - right? The default method there is the Wang et al. naive Bayesian classifier that is described in [this AEM paper](https://journals.asm.org/doi/10.1128/AEM.00062-07).

Basically... it looks at the kmer profile for sequences found in each genus (or whatever the lowest taxonomic level is) and then asks which kmer profile is most similar to what is found in the unknown sequence. It takes a random subset of the kmers from the unknown and reclassifies the unknown. It repeats drawing and classifying the random subset 100 times. It then finds the consensus classification across the 100 psueobootstraps and reports the plurality fraction of bootstraps that agree at each taxonomic level. By default, mothur returns only those classifications with 80% agreement/confidence. That might mean the genus/species level is dropped and only the family or higher taxonomic level is reported.

Because of the random drawing of pseudo bootstraps you can get run-to-run variation in classification. This is especially true if the confidence score is near 80%. Operationally, we don't see what you are seeing because our pipelines typically "unique" the sequences to only classify each sequence once. I guess we wouldn't know if we got lucky/unlucky in your case with our pipeline.

Pat
