### ISSUE TITLE
Randomness introduced by trim.seqs despite seed being set

### ISSUE THREAD

**Issue by AJTDaedalus** [mothur/mothur#859]
Hello, I am using mothur to do sequence analysis.  I am setting the seed as the first step of the batch command, and use this command to trim:

`trim.seqs(fasta=concat_seqs.fasta, qfile=concat_seqs.qual, maxambig=0, maxhomop=8, flip=T, bdiffs=1, pdiffs=2, qwindowaverage=15, qwindowsize=50)`

Before this command the fasta and qual files are identical between runs, but the concat_seqs.trim.fasta files differ in order, and all analyses downstream also differ I suspect because the order adds randomness despite the seed being set.

**Comment by mothur-westcott** [comment]
This is not due to the seed, but the fact that mothur's parallelization uses shared writing.  This means that when you run parallelized commands all the processes write to the output same file. The order they are allowed to write in is controlled by the operating system's task scheduler. You can sort the order of the reads in the file using the [sort.seqs](https://mothur.org/wiki/sort.seqs/) command

**Comment by AJTDaedalus** [comment]
Thanks!  That was my suspicion but wanted to make sure it was intended.  I had started using sort.seqs to try fixing it on Friday but it looks like multiple steps have this issue and when they go into classify.seqs in random order we get slightly different results even with a seed set.  I'll try sorting at every intermediate step and see if that resolves the randomness in the classification.
