### ISSUE TITLE
Primer step before mothur- Remove OTUs or list sequence found in negative controls from samples

### ISSUE THREAD

**Issue by JayalalKJ** [mothur/mothur#860]
Dear Mothur Team,

I am currently working on an analysis using Mothur v1.48.0 and would greatly appreciate your assistance with a few questions I've encountered.

Background: I am amplifying the V3-V4 region of the 16S rRNA gene using the primers 341F (ACTCCTACGGGAGGCAGCAG) and 806R (GGACTACHVGGGTWTCTAAT).

1. Building a Reference File for the V3-V4 Region
I have been attempting to build a reference file for the V3-V4 region using the following method. Could you please confirm if this approach is correct, or suggest any improvements?

#pcr.seqs(fasta=ecoli.16srrna.fasta, oligos=pcrTest.oligos)
#align.seqs(fasta=ecoli.16srrna.pcr.fasta, reference=silva.nr_v132.align)
#summary.seqs(fasta=ecoli.16srrna.pcr.align)
#pcr.seqs(fasta=silva.nr_v132.align, start=6428, end=23444, keepdots=FALSE)
#rename.file(input=silva.nr_v132.pcr.align, new=silva.v3.v4.fasta)

Additionally, if I am aiming for species-level resolution, which reference would you recommend for the best accuracy?

2. Proceeding after FastQC
I have processed my clean reads by removing tags and primers, and I have conducted a primary FastQC analysis. Is it acceptable to move directly into the Mothur pipeline after FastQC, or would you suggest any further preprocessing steps before initiating Mothur analysis?

3. Handling contaminants in Negative Controls 
In my analysis, both my negative controls (EB4) and actual samples have reported several bacterial OTUs. I suspect that the OTUs in the negative controls may represent contaminants, and I would like to remove them from the actual samples to ensure accurate results.

Could you advise on the best approach to identify and remove these shared OTUs using Mothur? Below is the current Mothur workflow I am using, what would be your suggestion here, to fix this!

#pcr.seqs(fasta=ecoli.16srrna.fasta, oligos=pcrTest.oligos)
#align.seqs(fasta=ecoli.16srrna.pcr.fasta, reference=silva.nr_v132.align)
#summary.seqs(fasta=ecoli.16srrna.pcr.align)
#pcr.seqs(fasta=silva.nr_v132.align, start=6428, end=23444, keepdots=FALSE)
#rename.file(input=silva.nr_v132.pcr.align, new=silva.v3.v4.fasta)
#make.file(inputdir=., type=fastq, prefix=stability)
#make.contigs(file=current)
#summary.seqs(fasta=stability.trim.contigs.fasta)
#screen.seqs(fasta=stability.trim.contigs.fasta, count=stability.contigs.count_table, maxambig=0, maxlength=450, maxhomop=8)
#unique.seqs(fasta=stability.trim.contigs.good.fasta, count=stability.contigs.good.count_table)
#align.seqs(fasta=stability.trim.contigs.good.unique.fasta, reference=silva.v3.v4.fasta)
#summary.seqs(fasta=stability.trim.contigs.good.unique.align)
#screen.seqs(fasta=current, count=current, start=1, end=17017)
#filter.seqs(fasta=current, vertical=T, trump=.)
#unique.seqs(fasta=current, count=current)
#pre.cluster(fasta=current, count=current, diffs=2)
#chimera.vsearch(fasta=current, count=current, dereplicate=T)
#classify.seqs(fasta=current, count=current, reference=silva.nr_v132.align, taxonomy=silva.nr_v132.tax, cutoff=80)
#remove.groups(fasta=current, count=current, taxonomy=current, groups=EB4)
#remove.lineage(fasta=current, count=current, taxonomy=current, taxon=Chloroplast-Mitochondria-unknown-Archaea-Eukaryota)
#cluster.split(fasta=current, count=current, taxonomy=current, splitmethod=classify, taxlevel=6, cutoff=0.03)
#make.shared(list=current, count=current, label=0.03)
#classify.otu(list=current, count=current, taxonomy=current, label=0.03)

Best-Jay

**Comment by pschloss** [comment]
Hi there - There's a lot of questions here. Let me do my best...

1. You cannot get species level names from 16S rRNA gene sequences. That's asking way too much of the gene. You need genome sequences to get species level identities.
2. I do not recommend using tools like FastQC prior to bringing your sequences into mothur. This type of trimming actually diminishes the quality of the assembled reads. You should start with `make.contigs` using the `oligos` option to remove barcode and primer sequences.
3. I don't recommend removing OTUs from biological samples that are also found in negative samples since an OTU is too broad a definition (sequence level would be better) and because the sequences may be real. Also, it's always possible that the samples contaminated the negative controls rather than the other way around. The best solution we have found is to leave all of the sequences were they are and proceed with your analysis. If you find an OTU that is rare and differentially abundant and overlaps with something in your negative controls, then you might look closer. 

Also, in the future these types of questions are best asked at forum.mothur.org.

Thanks!
Pat

**Comment by JayalalKJ** [comment]
Thanks pschols, I will ask these types of questions at forum.mothur.org :)
